# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
# Site Settings
locale: "en-US"
title: "Abha Bhole"
title_separator: "-"
subtitle:
name: "Abha Bhole"
description: "Abha Bhole - Projects and CV"
baseurl: "/sp26-portfolio-ABhole2025"   # Correct GitHub Pages style

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: dark

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /projects/:name/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
